[2023-02-03T12:33:03.480+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [queued]>
[2023-02-03T12:33:03.488+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [queued]>
[2023-02-03T12:33:03.488+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T12:33:03.488+0530] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-02-03T12:33:03.488+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T12:33:03.508+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-03 06:32:25.930956+00:00
[2023-02-03T12:33:03.518+0530] {standard_task_runner.py:55} INFO - Started process 25864 to run task
[2023-02-03T12:33:03.521+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'extract', 'manual__2023-02-03T06:32:25.930956+00:00', '--job-id', '3941', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmp1vkk2s0o']
[2023-02-03T12:33:03.522+0530] {standard_task_runner.py:83} INFO - Job 3941: Subtask extract
[2023-02-03T12:33:03.589+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-03T12:33:04.109+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T06:32:25.930956+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T06:32:25.930956+00:00
[2023-02-03T12:34:57.278+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 478, in extract
    elem = driver.find_element(By.CLASS_NAME,"tablebg")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=109.0.5414.119)
Stacktrace:
#0 0x55fa23ecd2a3 <unknown>
#1 0x55fa23c8bf77 <unknown>
#2 0x55fa23cc880c <unknown>
#3 0x55fa23cc8a71 <unknown>
#4 0x55fa23d02734 <unknown>
#5 0x55fa23ce8b5d <unknown>
#6 0x55fa23d0047c <unknown>
#7 0x55fa23ce8903 <unknown>
#8 0x55fa23cbbece <unknown>
#9 0x55fa23cbcfde <unknown>
#10 0x55fa23f1d63e <unknown>
#11 0x55fa23f20b79 <unknown>
#12 0x55fa23f0389e <unknown>
#13 0x55fa23f21a83 <unknown>
#14 0x55fa23ef6505 <unknown>
#15 0x55fa23f42ca8 <unknown>
#16 0x55fa23f42e36 <unknown>
#17 0x55fa23f5e333 <unknown>
#18 0x7fd782dfb609 start_thread

[2023-02-03T12:34:57.347+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=extract, execution_date=20230203T063225, start_date=20230203T070303, end_date=20230203T070457
[2023-02-03T12:34:57.412+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3941 for task extract (Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=109.0.5414.119)
Stacktrace:
#0 0x55fa23ecd2a3 <unknown>
#1 0x55fa23c8bf77 <unknown>
#2 0x55fa23cc880c <unknown>
#3 0x55fa23cc8a71 <unknown>
#4 0x55fa23d02734 <unknown>
#5 0x55fa23ce8b5d <unknown>
#6 0x55fa23d0047c <unknown>
#7 0x55fa23ce8903 <unknown>
#8 0x55fa23cbbece <unknown>
#9 0x55fa23cbcfde <unknown>
#10 0x55fa23f1d63e <unknown>
#11 0x55fa23f20b79 <unknown>
#12 0x55fa23f0389e <unknown>
#13 0x55fa23f21a83 <unknown>
#14 0x55fa23ef6505 <unknown>
#15 0x55fa23f42ca8 <unknown>
#16 0x55fa23f42e36 <unknown>
#17 0x55fa23f5e333 <unknown>
#18 0x7fd782dfb609 start_thread
; 25864)
[2023-02-03T12:34:57.460+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-03T12:34:57.522+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
