[2023-02-03T12:07:28.338+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [queued]>
[2023-02-03T12:07:28.349+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [queued]>
[2023-02-03T12:07:28.349+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T12:07:28.349+0530] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-02-03T12:07:28.349+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T12:07:28.368+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-03 06:32:25.930956+00:00
[2023-02-03T12:07:28.377+0530] {standard_task_runner.py:55} INFO - Started process 21332 to run task
[2023-02-03T12:07:28.380+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'extract', 'manual__2023-02-03T06:32:25.930956+00:00', '--job-id', '3939', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmp0jw193ah']
[2023-02-03T12:07:28.381+0530] {standard_task_runner.py:83} INFO - Job 3939: Subtask extract
[2023-02-03T12:07:28.448+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.extract manual__2023-02-03T06:32:25.930956+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-03T12:07:28.544+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T06:32:25.930956+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T06:32:25.930956+00:00
[2023-02-03T12:09:39.595+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 478, in extract
    elem = driver.find_element(By.CLASS_NAME,"tablebg")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x561cc1f742a3 <unknown>
#1 0x561cc1d32f77 <unknown>
#2 0x561cc1d6f80c <unknown>
#3 0x561cc1d6fa71 <unknown>
#4 0x561cc1da9734 <unknown>
#5 0x561cc1d8fb5d <unknown>
#6 0x561cc1da747c <unknown>
#7 0x561cc1d8f903 <unknown>
#8 0x561cc1d62ece <unknown>
#9 0x561cc1d63fde <unknown>
#10 0x561cc1fc463e <unknown>
#11 0x561cc1fc7b79 <unknown>
#12 0x561cc1faa89e <unknown>
#13 0x561cc1fc8a83 <unknown>
#14 0x561cc1f9d505 <unknown>
#15 0x561cc1fe9ca8 <unknown>
#16 0x561cc1fe9e36 <unknown>
#17 0x561cc2005333 <unknown>
#18 0x7fe80d43a609 start_thread

[2023-02-03T12:09:39.729+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=extract, execution_date=20230203T063225, start_date=20230203T063728, end_date=20230203T063939
[2023-02-03T12:09:39.816+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3939 for task extract (Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x561cc1f742a3 <unknown>
#1 0x561cc1d32f77 <unknown>
#2 0x561cc1d6f80c <unknown>
#3 0x561cc1d6fa71 <unknown>
#4 0x561cc1da9734 <unknown>
#5 0x561cc1d8fb5d <unknown>
#6 0x561cc1da747c <unknown>
#7 0x561cc1d8f903 <unknown>
#8 0x561cc1d62ece <unknown>
#9 0x561cc1d63fde <unknown>
#10 0x561cc1fc463e <unknown>
#11 0x561cc1fc7b79 <unknown>
#12 0x561cc1faa89e <unknown>
#13 0x561cc1fc8a83 <unknown>
#14 0x561cc1f9d505 <unknown>
#15 0x561cc1fe9ca8 <unknown>
#16 0x561cc1fe9e36 <unknown>
#17 0x561cc2005333 <unknown>
#18 0x7fe80d43a609 start_thread
; 21332)
[2023-02-03T12:09:39.871+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-03T12:09:39.976+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
