[2023-01-07T11:11:25.167+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.load scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T11:11:25.197+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.load scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T11:11:25.198+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T11:11:25.198+0530] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-01-07T11:11:25.199+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T11:11:25.251+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-06 00:00:00+00:00
[2023-01-07T11:11:25.269+0530] {standard_task_runner.py:55} INFO - Started process 5210 to run task
[2023-01-07T11:11:25.278+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'load', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '2940', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmpomp3ah0a']
[2023-01-07T11:11:25.282+0530] {standard_task_runner.py:83} INFO - Job 2940: Subtask load
[2023-01-07T11:11:25.402+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.load scheduled__2023-01-06T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-01-07T11:11:25.732+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T11:11:25.747+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 441, in load
    b4 = list(context['ti'].xcom_pull(task_ids='extract')[0])
TypeError: 'NoneType' object is not subscriptable
[2023-01-07T11:11:25.758+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=load, execution_date=20230106T000000, start_date=20230107T054125, end_date=20230107T054125
[2023-01-07T11:11:25.793+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 2940 for task load ('NoneType' object is not subscriptable; 5210)
[2023-01-07T11:11:25.822+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-07T11:11:25.850+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
