[2023-03-17T01:26:21.455+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: FX__Turnover.extract scheduled__2023-02-25T00:00:00+00:00 [queued]>
[2023-03-17T01:26:21.465+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: FX__Turnover.extract scheduled__2023-02-25T00:00:00+00:00 [queued]>
[2023-03-17T01:26:21.465+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T01:26:21.465+0530] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-03-17T01:26:21.465+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T01:26:21.482+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-25 00:00:00+00:00
[2023-03-17T01:26:21.495+0530] {standard_task_runner.py:55} INFO - Started process 845 to run task
[2023-03-17T01:26:21.499+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'FX__Turnover', 'extract', 'scheduled__2023-02-25T00:00:00+00:00', '--job-id', '4767', '--raw', '--subdir', 'DAGS_FOLDER/FX_turnover.py', '--cfg-path', '/tmp/tmpw3qabu2b']
[2023-03-17T01:26:21.500+0530] {standard_task_runner.py:83} INFO - Job 4767: Subtask extract
[2023-03-17T01:26:21.561+0530] {task_command.py:389} INFO - Running <TaskInstance: FX__Turnover.extract scheduled__2023-02-25T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-03-17T01:26:21.672+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=FX__Turnover
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-25T00:00:00+00:00
[2023-03-17T01:26:54.068+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/FX_turnover.py", line 141, in extract_fxturn
    python_button1[0].click()
IndexError: list index out of range
[2023-03-17T01:26:54.077+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=FX__Turnover, task_id=extract, execution_date=20230225T000000, start_date=20230316T195621, end_date=20230316T195654
[2023-03-17T01:26:54.102+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 4767 for task extract (list index out of range; 845)
[2023-03-17T01:26:54.131+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-17T01:26:54.154+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
