[2023-02-24T21:10:49.235+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nsdlfpi_and_rupee.send_email manual__2023-02-24T05:15:32.900302+00:00 [queued]>
[2023-02-24T21:10:49.244+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nsdlfpi_and_rupee.send_email manual__2023-02-24T05:15:32.900302+00:00 [queued]>
[2023-02-24T21:10:49.245+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-24T21:10:49.245+0530] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-02-24T21:10:49.245+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-24T21:10:49.262+0530] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_email> on 2023-02-24 05:15:32.900302+00:00
[2023-02-24T21:10:49.266+0530] {standard_task_runner.py:55} INFO - Started process 7859 to run task
[2023-02-24T21:10:49.269+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'nsdlfpi_and_rupee', 'send_email', 'manual__2023-02-24T05:15:32.900302+00:00', '--job-id', '4739', '--raw', '--subdir', 'DAGS_FOLDER/nsdl_and_rupee.py', '--cfg-path', '/tmp/tmpqqdqtnb4']
[2023-02-24T21:10:49.271+0530] {standard_task_runner.py:83} INFO - Job 4739: Subtask send_email
[2023-02-24T21:10:49.329+0530] {task_command.py:389} INFO - Running <TaskInstance: nsdlfpi_and_rupee.send_email manual__2023-02-24T05:15:32.900302+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-24T21:10:49.417+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=nsdlfpi_and_rupee
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-02-24T05:15:32.900302+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-24T05:15:32.900302+00:00
[2023-02-24T21:10:49.438+0530] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.8/dist-packages/airflow/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-02-24T21:10:49.439+0530] {email.py:229} INFO - Email alerting: attempt 1
[2023-02-24T21:11:18.055+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 59, in send_email
    return backend(
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
[2023-02-24T21:11:18.349+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=nsdlfpi_and_rupee, task_id=send_email, execution_date=20230224T051532, start_date=20230224T154049, end_date=20230224T154118
[2023-02-24T21:11:18.373+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 4739 for task send_email ([Errno 101] Network is unreachable; 7859)
[2023-02-24T21:11:27.042+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-24T21:11:27.058+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
