[2023-01-10T10:28:37.141+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.load scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2023-01-10T10:28:37.172+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.load scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2023-01-10T10:28:37.172+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T10:28:37.172+0530] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-01-10T10:28:37.172+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-10T10:28:37.206+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-07 00:00:00+00:00
[2023-01-10T10:28:37.220+0530] {standard_task_runner.py:55} INFO - Started process 592 to run task
[2023-01-10T10:28:37.226+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'load', 'scheduled__2023-01-07T00:00:00+00:00', '--job-id', '2979', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmp7q735jxe']
[2023-01-10T10:28:37.229+0530] {standard_task_runner.py:83} INFO - Job 2979: Subtask load
[2023-01-10T10:28:37.349+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.load scheduled__2023-01-07T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-01-10T10:28:37.516+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-07T00:00:00+00:00
[2023-01-10T10:28:37.530+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 441, in load
    b4 = list(context['ti'].xcom_pull(task_ids='extract')[0])
TypeError: 'NoneType' object is not subscriptable
[2023-01-10T10:28:37.538+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=load, execution_date=20230107T000000, start_date=20230110T045837, end_date=20230110T045837
[2023-01-10T10:28:37.573+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 2979 for task load ('NoneType' object is not subscriptable; 592)
[2023-01-10T10:28:37.602+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-10T10:28:37.630+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
