[2023-02-03T11:44:01.056+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:44:01.071+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:44:01.071+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:44:01.071+0530] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-02-03T11:44:01.071+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:44:01.093+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-03 06:05:58.663215+00:00
[2023-02-03T11:44:01.101+0530] {standard_task_runner.py:55} INFO - Started process 20355 to run task
[2023-02-03T11:44:01.105+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'extract', 'manual__2023-02-03T06:05:58.663215+00:00', '--job-id', '3924', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmph3hp2w02']
[2023-02-03T11:44:01.108+0530] {standard_task_runner.py:83} INFO - Job 3924: Subtask extract
[2023-02-03T11:44:01.171+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-03T11:44:01.331+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T06:05:58.663215+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T06:05:58.663215+00:00
[2023-02-03T11:45:41.408+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 478, in extract
    elem = driver.find_element(By.CLASS_NAME,"tablebg")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x5641fa7932a3 <unknown>
#1 0x5641fa551f77 <unknown>
#2 0x5641fa58e80c <unknown>
#3 0x5641fa58ea71 <unknown>
#4 0x5641fa5c8734 <unknown>
#5 0x5641fa5aeb5d <unknown>
#6 0x5641fa5c647c <unknown>
#7 0x5641fa5ae903 <unknown>
#8 0x5641fa581ece <unknown>
#9 0x5641fa582fde <unknown>
#10 0x5641fa7e363e <unknown>
#11 0x5641fa7e6b79 <unknown>
#12 0x5641fa7c989e <unknown>
#13 0x5641fa7e7a83 <unknown>
#14 0x5641fa7bc505 <unknown>
#15 0x5641fa808ca8 <unknown>
#16 0x5641fa808e36 <unknown>
#17 0x5641fa824333 <unknown>
#18 0x7f722da03609 start_thread

[2023-02-03T11:45:41.418+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=extract, execution_date=20230203T060558, start_date=20230203T061401, end_date=20230203T061541
[2023-02-03T11:45:41.433+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3924 for task extract (Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x5641fa7932a3 <unknown>
#1 0x5641fa551f77 <unknown>
#2 0x5641fa58e80c <unknown>
#3 0x5641fa58ea71 <unknown>
#4 0x5641fa5c8734 <unknown>
#5 0x5641fa5aeb5d <unknown>
#6 0x5641fa5c647c <unknown>
#7 0x5641fa5ae903 <unknown>
#8 0x5641fa581ece <unknown>
#9 0x5641fa582fde <unknown>
#10 0x5641fa7e363e <unknown>
#11 0x5641fa7e6b79 <unknown>
#12 0x5641fa7c989e <unknown>
#13 0x5641fa7e7a83 <unknown>
#14 0x5641fa7bc505 <unknown>
#15 0x5641fa808ca8 <unknown>
#16 0x5641fa808e36 <unknown>
#17 0x5641fa824333 <unknown>
#18 0x7f722da03609 start_thread
; 20355)
[2023-02-03T11:45:41.476+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-03T11:45:41.497+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
