[2023-02-03T11:40:01.088+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:40:01.115+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:40:01.115+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:40:01.115+0530] {taskinstance.py:1284} INFO - Starting attempt 2 of 4
[2023-02-03T11:40:01.116+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:40:01.147+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-03 06:05:58.663215+00:00
[2023-02-03T11:40:01.153+0530] {standard_task_runner.py:55} INFO - Started process 20195 to run task
[2023-02-03T11:40:01.158+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'extract', 'manual__2023-02-03T06:05:58.663215+00:00', '--job-id', '3923', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmps0for54p']
[2023-02-03T11:40:01.163+0530] {standard_task_runner.py:83} INFO - Job 3923: Subtask extract
[2023-02-03T11:40:01.283+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-03T11:40:01.396+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T06:05:58.663215+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T06:05:58.663215+00:00
[2023-02-03T11:41:57.380+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 478, in extract
    elem = driver.find_element(By.CLASS_NAME,"tablebg")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x55648edcd2a3 <unknown>
#1 0x55648eb8bf77 <unknown>
#2 0x55648ebc880c <unknown>
#3 0x55648ebc8a71 <unknown>
#4 0x55648ec02734 <unknown>
#5 0x55648ebe8b5d <unknown>
#6 0x55648ec0047c <unknown>
#7 0x55648ebe8903 <unknown>
#8 0x55648ebbbece <unknown>
#9 0x55648ebbcfde <unknown>
#10 0x55648ee1d63e <unknown>
#11 0x55648ee20b79 <unknown>
#12 0x55648ee0389e <unknown>
#13 0x55648ee21a83 <unknown>
#14 0x55648edf6505 <unknown>
#15 0x55648ee42ca8 <unknown>
#16 0x55648ee42e36 <unknown>
#17 0x55648ee5e333 <unknown>
#18 0x7f48bdfde609 start_thread

[2023-02-03T11:41:57.391+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=extract, execution_date=20230203T060558, start_date=20230203T061001, end_date=20230203T061157
[2023-02-03T11:41:57.411+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3923 for task extract (Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x55648edcd2a3 <unknown>
#1 0x55648eb8bf77 <unknown>
#2 0x55648ebc880c <unknown>
#3 0x55648ebc8a71 <unknown>
#4 0x55648ec02734 <unknown>
#5 0x55648ebe8b5d <unknown>
#6 0x55648ec0047c <unknown>
#7 0x55648ebe8903 <unknown>
#8 0x55648ebbbece <unknown>
#9 0x55648ebbcfde <unknown>
#10 0x55648ee1d63e <unknown>
#11 0x55648ee20b79 <unknown>
#12 0x55648ee0389e <unknown>
#13 0x55648ee21a83 <unknown>
#14 0x55648edf6505 <unknown>
#15 0x55648ee42ca8 <unknown>
#16 0x55648ee42e36 <unknown>
#17 0x55648ee5e333 <unknown>
#18 0x7f48bdfde609 start_thread
; 20195)
[2023-02-03T11:41:57.457+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-03T11:41:57.479+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
